<section id="create-tours" class="mt-8 scroll-mt-28 bg-white p-6 shadow-[0_24px_70px_rgba(5,24,20,0.1)] md:p-9">
    <div class="flex flex-col justify-between gap-3 border-b border-ink/10 pb-6 sm:flex-row sm:items-end"><div><p class="text-sm font-semibold text-brand-600">Thêm trực tiếp</p><h2 class="mt-2 text-3xl font-semibold tracking-[-0.04em] text-ink">Thêm tour</h2></div><p class="text-xs text-ink/45">Các trường có dấu * bắt buộc nhập.</p></div>
    <form method="post" enctype="multipart/form-data" action="{{ route('admin.tours.store') }}" class="mt-7 grid gap-5 md:grid-cols-2">
        @csrf
        <label class="text-sm font-semibold">Tên tour *<input name="name" required class="mt-2 w-full border border-ink/15 bg-cream px-4 py-3 font-normal outline-none focus:border-brand-500"></label>
        <label class="text-sm font-semibold">Slug *<input name="slug" required pattern="[A-Za-z0-9_-]+" class="mt-2 w-full border border-ink/15 bg-cream px-4 py-3 font-normal outline-none focus:border-brand-500"></label>
        <label class="text-sm font-semibold">Điểm đến<select name="destination_id" class="mt-2 w-full border border-ink/15 bg-cream px-4 py-3 font-normal outline-none focus:border-brand-500"><option value="">Chưa chọn</option>@foreach($destinations as $destination)<option value="{{ $destination->id }}">{{ $destination->name }}</option>@endforeach</select></label>
        <label class="text-sm font-semibold">Số ngày *<input name="duration_days" type="number" min="1" value="1" required class="mt-2 w-full border border-ink/15 bg-cream px-4 py-3 font-normal outline-none focus:border-brand-500"></label>
        <label class="text-sm font-semibold">Số đêm<input name="duration_nights" type="number" min="0" value="0" class="mt-2 w-full border border-ink/15 bg-cream px-4 py-3 font-normal outline-none focus:border-brand-500"></label>
        <label class="text-sm font-semibold md:col-span-2">Mô tả ngắn *<textarea name="short_description" rows="3" required class="mt-2 w-full border border-ink/15 bg-cream px-4 py-3 font-normal outline-none focus:border-brand-500"></textarea></label>
        <label class="text-sm font-semibold md:col-span-2">Mô tả chi tiết *<textarea name="description" rows="6" required class="mt-2 w-full border border-ink/15 bg-cream px-4 py-3 font-normal outline-none focus:border-brand-500"></textarea></label>
        <label class="text-sm font-semibold">Giá bán *<input name="base_price" type="number" min="0" step="0.01" required class="mt-2 w-full border border-ink/15 bg-cream px-4 py-3 font-normal outline-none focus:border-brand-500"></label>
        <label class="text-sm font-semibold">Tiền tệ *<select name="currency" required class="mt-2 w-full border border-ink/15 bg-cream px-4 py-3 font-normal outline-none focus:border-brand-500">@foreach(\App\Support\MoneyFormatter::SUPPORTED_CURRENCIES as $currency => $label)<option value="{{ $currency }}" @selected($currency === \App\Support\MoneyFormatter::DEFAULT_CURRENCY)>{{ $label }}</option>@endforeach</select></label>
        <label class="text-sm font-semibold">Thứ tự *<input name="sort_order" type="number" min="0" value="0" required class="mt-2 w-full border border-ink/15 bg-cream px-4 py-3 font-normal outline-none focus:border-brand-500"></label>
        <label class="text-sm font-semibold">Badge<input name="badge" class="mt-2 w-full border border-ink/15 bg-cream px-4 py-3 font-normal outline-none focus:border-brand-500"></label>
        <div class="md:col-span-2">@include('admin.tours.service-picker', ['selectedServiceIds' => []])</div>
        <div class="md:col-span-2">@include('admin.tours.product-picker', ['selectedProductIds' => []])</div>
        <label class="text-sm font-semibold md:col-span-2">Ảnh tour<span class="mt-3 grid gap-4 md:grid-cols-[10rem_1fr] md:items-center"><span data-image-preview class="grid aspect-[4/3] place-items-center overflow-hidden bg-sand text-xs text-ink/40">Xem trước</span><input data-image-input type="file" name="image" accept="image/jpeg,image/png,image/webp" class="block w-full cursor-pointer border border-dashed border-ink/25 bg-cream px-4 py-5 text-sm file:mr-3 file:rounded-full file:border-0 file:bg-ink file:px-4 file:py-2 file:text-white"></span></label>
        <div class="flex flex-wrap gap-6 md:col-span-2"><label class="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" name="is_featured" value="1"> Nổi bật</label><label class="flex items-center gap-2 text-sm font-semibold"><input type="checkbox" name="is_active" value="1" checked> Hoạt động</label></div>
        <button class="accent-contrast rounded-full bg-coral px-7 py-3 text-sm font-semibold md:col-span-2 md:justify-self-start">Thêm tour</button>
    </form>
</section>
